/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.controller.MyController', {
    extend: 'Ext.app.Controller',

    config: {
        views: [
            'surveyPanel'
        ],

        refs: {
            surveyVenueLabel: 'surveyPanel'
        },

        control: {
            "list": {
                itemtap: 'onListItemTap'
            }
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        console.log(record.get('name'));
         Ext.Viewport.setActiveItem('surveypanel',{
                                    type: "slide",
                                    direction: "left"
                                });
    }

});