/*
 * File: app/view/addVenuePanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.addVenuePanel', {
    extend: 'Ext.Panel',
    alias: 'widget.addvenuepanel',

    requires: [
        'Ext.Container',
        'Ext.field.Number',
        'Ext.Label',
        'Ext.field.Slider',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'textfield',
                        docked: 'top',
                        label: 'Name'
                    },
                    {
                        xtype: 'numberfield',
                        docked: 'top',
                        label: 'Location',
                        ui: 'text'
                    },
                    {
                        xtype: 'label'
                    },
                    {
                        xtype: 'sliderfield',
                        clearIcon: false,
                        label: ''
                    },
                    {
                        xtype: 'label',
                        docked: 'left',
                        html: 'emo 1'
                    },
                    {
                        xtype: 'label',
                        docked: 'right',
                        html: 'emo 2'
                    }
                ]
            },
            {
                xtype: 'button',
                docked: 'bottom',
                ui: 'action-round',
                text: 'MyButton3'
            }
        ]
    }

});