/*
 * File: app/view/SignInPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.SignInPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.signinpanel',

    requires: [
        'Ext.Label',
        'Ext.field.Password',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'label',
                html: 'Please, authorise'
            },
            {
                xtype: 'textfield',
                id: 'signInUsernameField',
                label: 'Username',
                labelAlign: 'right',
                labelWidth: '35%'
            },
            {
                xtype: 'passwordfield',
                id: 'signInPasswordField',
                label: 'Password',
                labelAlign: 'right',
                labelWidth: '35%'
            },
            {
                xtype: 'button',
                handler: function(button, e) {
                    var username = Ext.getCmp('signInUsernameField').getValue();
                    var pass = Ext.getCmp('signInPasswordField').getValue();
                    console.log('Username: ' + username );
                    console.log('Password: ' + pass );

                    Ext.data.JsonP.request({

                        url: 'http://115.146.86.216:8080/TransNet/services/SurveyBO/Login',
                        params: {
                            username: username,
                            pass: pass,
                            format: 'json'
                        },
                        callbackKey: 'callback',
                        success: function (response) {
                            alert('Working!');
                            console.log(response);
                        },
                        failure: function (response) {
                            alert('Not working!');
                            console.log(response);
                        },
                        callback: function(successful, data){
                            alert(data);
                        }
                    });

                    Ext.Viewport.setActiveItem('surveypanel',{
                        type: "slide",
                        direction: "left"
                    });
                },
                docked: 'bottom',
                ui: 'action-round',
                text: 'Submit'
            }
        ]
    }

});