/*
 * File: app/view/SignUpPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.SignUpPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.signuppanel',

    requires: [
        'Ext.Label',
        'Ext.field.Password',
        'Ext.Container',
        'Ext.field.Radio',
        'Ext.Button'
    ],

    config: {
        id: 'signinpanel',
        items: [
            {
                xtype: 'label',
                docked: 'top',
                html: 'Please, choose your login and password'
            },
            {
                xtype: 'textfield',
                id: 'signUpUsernameField',
                label: 'Username',
                labelAlign: 'right',
                labelWidth: '35%'
            },
            {
                xtype: 'passwordfield',
                id: 'signUpPasswordField',
                label: 'Password',
                labelAlign: 'right',
                labelWidth: '35%'
            },
            {
                xtype: 'label',
                html: 'Tell us about yourself'
            },
            {
                xtype: 'textfield',
                id: 'emailField',
                label: 'Email',
                labelWidth: '40%'
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'radiofield',
                        docked: 'left',
                        label: 'Male',
                        labelWidth: '60%',
                        name: 'gender',
                        value: 'male'
                    },
                    {
                        xtype: 'radiofield',
                        centered: false,
                        docked: 'right',
                        label: 'Female',
                        labelAlign: 'right',
                        labelWidth: '60%',
                        name: 'gender',
                        value: 'female'
                    }
                ]
            },
            {
                xtype: 'textfield',
                id: 'ageField',
                label: 'Age',
                labelWidth: '40%',
                ui: 'number'
            },
            {
                xtype: 'textfield',
                id: 'occupationField',
                label: 'Occupation',
                labelWidth: '40%'
            },
            {
                xtype: 'button',
                handler: function(button, e) {
                    console.log('Username: ' + Ext.getCmp('signUpUsernameField').getValue());
                    console.log('Password: ' + Ext.getCmp('signUpPasswordField').getValue());
                    console.log('email: ' + Ext.getCmp('emailField').getValue());
                    console.log('age: ' + Ext.getCmp('ageField').getValue());
                    console.log('occupation: ' + Ext.getCmp('occupationField').getValue());
                    console.log('gender: ' + Ext.ComponentQuery.query('radiofield[name=gender]'));

                    Ext.Viewport.setActiveItem('surveypanel',{
                        type: "slide",
                        direction: "left"
                    });
                },
                docked: 'bottom',
                ui: 'action-round',
                text: 'Submit'
            }
        ]
    }

});