/*
 * File: app/view/SignUpPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.SignUpPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.signuppanel',

    requires: [
        'Ext.Label',
        'Ext.field.Password',
        'Ext.Container',
        'Ext.field.Radio',
        'Ext.Button'
    ],

    config: {
        id: 'signinpanel',
        style: 'background-color: #FFF',
        items: [
            {
                xtype: 'label',
                docked: 'top',
                html: 'Please, choose your login and password'
            },
            {
                xtype: 'textfield',
                border: 1,
                id: 'signUpUsernameField',
                style: '\'border-color: blue; border-style: solid;\',',
                label: 'Login'
            },
            {
                xtype: 'passwordfield',
                border: 1,
                id: 'signUpPasswordField',
                style: '\'border-color: blue; border-style: solid;\',',
                label: 'Password'
            },
            {
                xtype: 'label',
                html: 'Tell us about yourself'
            },
            {
                xtype: 'textfield',
                border: 1,
                id: 'emailField',
                padding: '',
                style: '\'border-color: blue; border-style: solid;\'',
                label: 'Email'
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'radiofield',
                        docked: 'left',
                        minWidth: '50%',
                        label: 'Male',
                        labelWidth: '60%',
                        name: 'gender',
                        value: 'male'
                    },
                    {
                        xtype: 'radiofield',
                        centered: false,
                        docked: 'right',
                        minWidth: '50%',
                        label: 'Female',
                        labelAlign: 'right',
                        labelWidth: '40%',
                        labelWrap: true,
                        name: 'gender',
                        value: 'female'
                    }
                ]
            },
            {
                xtype: 'textfield',
                border: 1,
                id: 'ageField',
                padding: '',
                style: '\'border-color: blue; border-style: solid;\',',
                label: 'Age',
                ui: 'number'
            },
            {
                xtype: 'textfield',
                border: 1,
                id: 'occupationField',
                style: '\'border-color: blue; border-style: solid;\',',
                label: 'Role'
            },
            {
                xtype: 'button',
                handler: function(button, e) {
                    var login = Ext.getCmp('signUpUsernameField').getValue();
                    var pass = Ext.getCmp('signUpPasswordField').getValue();
                    var email = Ext.getCmp('emailField').getValue();
                    var gender = Ext.ComponentQuery.query('radiofield[name=gender]')[0].getGroupValue();
                    var age = Ext.getCmp('ageField').getValue();
                    var role = Ext.getCmp('occupationField').getValue();
                    console.log('Username: ' + login);
                    console.log('Password: ' + pass);
                    console.log('email: ' + email);
                    console.log('age: ' + age);
                    console.log('occupation: ' + role);
                    console.log('gender: ' + gender);

                    Ext.data.JsonP.request({

                        url: 'http://115.146.86.216:8080/TransNet/services/SurveyBO/CreateUser',
                        params: {
                            format: 'json',
                            response: 'application/jsonp',
                            userdetails: login,
                            userdetails: pass,
                            userdetails: email,
                            userdetails: gender,
                            userdetails: age,
                            userdetails: role
                        },
                        callbackKey: 'callback',
                        success: function (response) {
                            alert('Working!');
                            console.log(response);
                        },
                        failure: function (response) {
                            alert('Not working!');
                            console.log(response);
                        },
                        callback: function(successful, data){
                            alert(data);
                        }
                    });

                    Ext.Viewport.setActiveItem('surveypanel',{
                        type: "slide",
                        direction: "left"
                    });
                },
                docked: 'bottom',
                ui: 'action-round',
                text: 'Submit'
            }
        ]
    }

});