/*
 * File: app/view/surveyPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('TranSafe.view.surveyPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.surveypanel',

    requires: [
        'Ext.Label',
        'Ext.Container',
        'Ext.Img',
        'Ext.field.Slider',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'label',
                html: 'Venue: ',
                id: 'venueLblSurvey'
            },
            {
                xtype: 'container',
                items: [
                    {
                        xtype: 'container',
                        docked: 'top',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_happy.jpg'
                            },
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_sad.jpg'
                            },
                            {
                                xtype: 'sliderfield',
                                docked: 'top',
                                width: '',
                                clearIcon: false,
                                label: '',
                                labelAlign: 'top',
                                value: [
                                    5
                                ],
                                maxValue: 10
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        width: '',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_excited.jpg'
                            },
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 70,
                                width: 48,
                                src: 'Emoticons/emotion_bored.jpg'
                            },
                            {
                                xtype: 'sliderfield',
                                docked: 'top',
                                width: '',
                                clearIcon: false,
                                label: '',
                                labelAlign: 'top',
                                value: [
                                    5
                                ],
                                maxValue: 10
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_safe.jpg'
                            },
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 70,
                                width: 48,
                                src: 'Emoticons/emotion_scared.jpg'
                            },
                            {
                                xtype: 'sliderfield',
                                docked: 'top',
                                width: '',
                                clearIcon: false,
                                label: '',
                                labelAlign: 'top',
                                value: [
                                    5
                                ],
                                maxValue: 10
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        items: [
                            {
                                xtype: 'image',
                                docked: 'left',
                                height: 70,
                                width: 50,
                                src: 'Emoticons/emotion_peaceful.jpg'
                            },
                            {
                                xtype: 'image',
                                docked: 'right',
                                height: 70,
                                width: 48,
                                src: 'Emoticons/emotion_angry.jpg'
                            },
                            {
                                xtype: 'sliderfield',
                                docked: 'top',
                                width: '',
                                clearIcon: false,
                                label: '',
                                labelAlign: 'top',
                                value: [
                                    5
                                ],
                                maxValue: 10
                            }
                        ]
                    },
                    {
                        xtype: 'label'
                    }
                ]
            },
            {
                xtype: 'button',
                handler: function(button, e) {
                    Ext.Ajax.request({
                        url: 'proxy.php?url=http://115.146.86.216:8080/TransNet/services/SurveyBO/SumTypeOfFeeling?location=location1',
                        success: function (response, options) { console.log(response); },
                        failure: function (response, options) { console.log('no!');}
                    });
                },
                docked: 'bottom',
                itemId: 'mybutton2',
                ui: 'action-round',
                text: 'Send to web service'
            }
        ]
    }

});